#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 12 21:36:41 2018

@author: xsxsz
"""

a=[1,2,3,4]
print(a)
print('----------')
a.append(5)
print(a)
print('----------')
for i in range(10):
    if i%2==0:
        a.append(i)
print(a)